import {
  Aries,
  Taurus,
  Gemini,
  Cancer,
  Leo,
  Virgo,
  Libra,
  Scorpio,
  Sagittarius,
  Capricorn,
  Aquarius,
  Pisces,
} from '~/images';

export const signs = [
  {
    title: 'Aries',
    description: 'Brave, adventurous, and a pioneer',
    modality: 'Cardinal',
    element: 'Fire',
    imageSrc: Aries,
  },
  {
    title: 'Taurus',
    description: 'Dependable, sensual, stubborn, materialistic, practical',
    modality: 'Fixed',
    element: 'Earth',
    imageSrc: Taurus,
  },
  {
    title: 'Gemini ',
    description: 'Communicative, intellectual, adaptable, curious, restless',
    modality: 'Mutable',
    element: 'Air',
    imageSrc: Gemini,
  },
  {
    title: 'Cancer',
    description: 'Emotional, nurturing, protective, intuitive, moody',
    modality: 'Cardinal',
    element: 'Water',
    imageSrc: Cancer,
  },
  {
    title: 'Leo',
    description: 'Dramatic, confident, generous, loyal, proud',
    modality: 'Fixed',
    element: 'Fire',
    imageSrc: Leo,
  },
  {
    title: 'Virgo',
    description: 'Analytical, practical, detail-oriented, critical, modest',
    modality: 'Mutable',
    element: 'Earth',
    imageSrc: Virgo,
  },
  {
    title: 'Libra',
    description: 'Diplomatic, artistic, sociable, indecisive, fair',
    modality: 'Cardinal',
    element: 'Air',
    imageSrc: Libra,
  },
  {
    title: 'Scorpio',
    description: 'Intense, passionate, secretive, powerful, penetrating',
    modality: 'Fixed',
    element: 'Water',
    imageSrc: Scorpio,
  },
  {
    title: 'Sagittarius',
    description:
      'Optimistic, freedom-loving, philosophical, blunt, adventurous',
    modality: 'Mutable',
    element: 'Fire',
    imageSrc: Sagittarius,
  },
  {
    title: 'Capricorn',
    description: 'Ambitious, disciplined, practical, cautious, conservative',
    modality: 'Cardinal',
    element: 'Earth',
    imageSrc: Capricorn,
  },
  {
    title: 'Aquarius',
    description: 'Innovative, humanitarian, detached, rebellious, intellectual',
    modality: 'Fixed',
    element: 'Air',
    imageSrc: Aquarius,
  },
  {
    title: 'Pisces',
    description: 'Compassionate, artistic, intuitive, sensitive, escapist',
    modality: 'Mutable',
    element: 'Water',
    imageSrc: Pisces,
  },
];
